### ISSUE TITLE
Request: Mesas and Canyons

### ISSUE THREAD

**Issue by erichlof** [IceCreamYou/THREE.Terrain#1]
@IceCreamYou 

Hi Isaac,
Love your work with Three.js terrains!  I have starred your repo and check back regularly for updates.

I have a feature request: the ability to create random mesas, buttes, and canyons.  I'm imagining the old "Road Runner" cartoons.  :)  

Here's a couple of images of desert landscapes:
http://www.mrwallpaper.com/wallpapers/Canyons-Red-Mesas-Canyons-1920x1200.jpg
and
http://www.wallpaperhi.com/thumbnails/detail/20120224/mesas%20canyons%20rivers%201600x1200%20wallpaper_www.wallpaperhi.com_41.jpg
and lastly,
http://www.scienceclarified.com/landforms/images/ueol_02_img0075.jpg

One of the ingredients is that the shelf or ceiling remains flat on top and then the rest drops off all around, creating inverted islands.  Is there a mathematical way of describing this natural phenomenon in your terrain plug-in?  Something that you could add to THREE.Terrain.js maybe in the future?

The reason I'm asking is that I am a game programmer using Three.js for desktop/mobile gameplay, and I have a couple of ideas for games that could use your terrain engine.  Here's a link to my first completed Three.js game:
https://github.com/erichlof/SpacePong3D

Asteroids in first-person 3D is next in the pipeline (doesn't look like much now, it's a WIP): https://github.com/erichlof/AsteroidPatrol3D

Again, great job on your terrain work.  I look forward to future updates!
Thanks,
-Erich

**Comment by IceCreamYou** [comment]
Glad you're interested in the project!

I just committed a new "steps" feature that makes an attempt at this. Try playing with it in the [demo viewer](https://icecreamyou.github.io/THREE.Terrain/) and see what you think. It goes pretty well with the Simplex method and the EaseInOut filter. (Try increasing the maxHeight to get a better effect.)

The way this works is it does a filtering pass that takes the output from other terrain generation functions and divides it into levels.

I can think of two other approaches:
- Something I call "feature picking," which is the idea of picking a random location and placing some kind of feature there like a mesa or hill. [This](http://www.wolframalpha.com/input/?i=1.25*min%280.8%2C+2e^-%28x^2%2By^2%29%29) seems to be a good starting candidate for mathematically modeling a mesa
- Coming up with a method that could create "faults" along which significant height changes could occur, probably by using some variation on Brownian walks. This is nontrivial and probably not a lot better than what I just implemented.

I'll probably implement something that looks like the first approach at some point. :smiley:

**Comment by erichlof** [comment]
@IceCreamYou 
Wow thank you so much Isaac!  The new steps feature is exactly what I was looking for!  Playing around with the settings I was able to create mesas (that stick up like mountains, Monument Valley style), stepped layers (Grand Canyon style), and fault-line canyons with a smooth, flat top shelf that erodes down to another flat ground (Canyonlands NP style).  Maybe a river could be placed on the bottom flat-shelf or ground level.

But in any case, this is really cool!  Back in 2001 I made a terrain artillery-style game in OpenGL  in C for Windows, called Virtual Bombard.  Here are some old screenshots from my game:

![](http://megagames.com/sites/default/files/game-content-images/virbomb_l1.jpg)

![](http://megagames.com/sites/default/files/game-content-images/virbomb_l2.jpg)

Just messing around with Math.sin, .cos, .tan, etc I was able to get some pretty neat random terrains.  But your terrain project goes way past what I was able to do just tinkering around with random trig functions.  I wanted to re-do this game using Three.js and now I actually have access to an awesome terrain plugin!

Thanks again - I'll keep checking back for more updates.  :)

**Comment by IceCreamYou** [comment]
Glad it's working for you! I'll look forward to seeing what you make :smiley:

It's also worth noting that the Steps filter is composable, so you can mix it in with other algorithms like DiamondSquare using `THREE.Terrain.MultiPass` if you want results to be a little less flat.

**Comment by erichlof** [comment]
Oh I hadn't thought of that - thanks for the tip!  :)
