### ISSUE TITLE
Texture Repeating

### ISSUE THREAD

**Issue by maemaemae3** [IceCreamYou/THREE.Terrain#16]
Sorry to ask a question again and again. I have another question.
I want to get blended texture shader material repeated like this:
![2](https://user-images.githubusercontent.com/6958342/52040102-bafe2880-2579-11e9-910f-8eb37e929f6c.png)

so I changed the code like this:
```javascript
/* at line 1694~ */

for (var i = 0, l = textures.length; i < l; i++) {
    // Uniforms
    textures[i].texture.wrapS = textures[i].wrapT = THREE.RepeatWrapping;
    textures[i].texture.repeat.set( 3, 3 ); // I changed this line
    textures[i].texture.needsUpdate = true;
    uniforms['texture_' + i] = {
        type: 't',
        value: textures[i].texture,
    };
```
However, the result was like this:
![default](https://user-images.githubusercontent.com/6958342/52042865-9a39d100-2581-11e9-8309-508235c64b56.png)

in the first row, texture repeating seems to done correctly, but it's collapsed from the next.
I can write shadermaterial with myself, but I want to use this lib because it's extremely useful.

Thank you in advance!

**Comment by IceCreamYou** [comment]
Sorry for not responding to this 😬

Unfortunately this library is mostly for the math of making shapes that look terrain-like, and I'm unable to help with Three.js texturing issues. This sounds like it's solvable without modifying this library, so I suggest asking on StackOverflow.
