### ISSUE TITLE
Island with a hill, how?

### ISSUE THREAD

**Issue by mattes3** [IceCreamYou/THREE.Terrain#24]
Hi, Isaac,

I'm trying to create an island with a hill in one corner and a more or less flat area on the rest of the island that I can fill with villages, etc. However, I'm unable to succeed. The large flat area does not appear. Maybe I do not understand what the parameters of the terrain really do.

What would be a good way to do this? Which combination of the `heightmap`, the `easing`, and the `after` parameters would be needed to make it happen? Got a small code sample?

Best...
Matthias

**Comment by IceCreamYou** [comment]
> Which combination of the heightmap, the easing, and the after parameters would be needed to make it happen?

None of these. Basically you call [`THREE.Terrain.Influence`](https://github.com/IceCreamYou/THREE.Terrain/blob/gh-pages/src/influences.js) and pass it relevant attributes of the terrain plus a function describing the shape you want (e.g. `THREE.Terrain.Influences.Hill`). You could make that call in an `after` callback but it's not necessary unless `useBufferGeometry` is `true`.

Feel free to reopen this issue if that doesn't answer your question. A sample of the code you're hoping will apply the influence would help clarify what could be going wrong.

**Comment by mattes3** [comment]
Got it. Thanks!
