### ISSUE TITLE
generateBlendedMaterial to support normalMaps / StandardMeshMaterial.

### ISSUE THREAD

**Issue by campbellgoe** [IceCreamYou/THREE.Terrain#27]
generateBlendedMaterial seems to be designed to support LambertMeshMaterial.

Lambert material does not support normal maps, whereas StandardMeshMaterial does via `normalMap`.

Below are two screenshots showing the difference between a blended texture and a single texture with a normalMap.

It would be great to have blend textures with normal maps.

Single texture using StandardMeshMaterial with normalMap:
![sand with normalMap](https://i.ibb.co/5FzHtYD/Screenshot-2019-08-03-at-21-32-20.png)

Blend of 2 textures made with generateBlendedMaterial:
![blended sand](https://i.ibb.co/gd3PH10/Screenshot-2019-08-03-at-21-33-07.png)

**Comment by IceCreamYou** [comment]
`generateBlendedMaterial` was written as a demo in 2014, basically a copy of the Lambert material in Three.js r67. 5 years later, at Three.js r107, `generateBlendedMaterial` has not kept up. But as much as I'd like it to work well for everyone, it's not the focus of this library, and I'm not actively developing THREE.Terrain anyway, so I don't expect to be the person who changes that.

The good news is that there's actually [not that much](https://github.com/IceCreamYou/THREE.Terrain/blob/gh-pages/src/materials.js) that `generateBlendedMaterial` does. It's basically just a copy of Lambert material with a small edit to interpolate colors. So if you want to explore doing something similar with a different base material, hopefully it wouldn't be too much work. I would certainly accept a PR 🙂

**Comment by campbellgoe** [comment]
MeshStandardMaterial supports displacements maps:

> .displacementMap : Texture
> The displacement map affects the position of the mesh's vertices. Unlike other maps which only affect the light and shade of the material the displaced vertices can cast shadows, block other objects, and otherwise act as real geometry. The displacement texture is an image where the value of each pixel (white being the highest) is mapped against, and repositions, the vertices of the mesh.

and displacementScale.

Additionally it supports normal maps, enabling nicer looking textures with directional lights.

I believe the functionality of terrain generation could be implementation by creating a set of 2d noise and using that as the displacementMap of a Standard material on a plane.

I have yet to play with it, but I plan on doing so.

**Comment by IceCreamYou** [comment]
`THREE.Terrain` [supports](https://github.com/IceCreamYou/THREE.Terrain#exporting-and-importing) exporting the generated terrain to an image. This image can be passed to the `THREE.Texture` constructor to create a texture that can be used for a `MeshStandardMaterial.displacementMap`. That won't help with blending materials but it's a roundabout way to get a terrain shape. The caveat is that you lose some precision, because displacement maps have only 256 possible values for each pixel, whereas terrains generated the normal way can place vertices at any height. This can be noticeable if your camera is closer to the ground than about 4% of the terrain's height range.

**Comment by IceCreamYou** [comment]
Thanks to #29 for making it possible, I just pushed a change to allow passing a material instance as a second parameter to `generateBlendedMaterial`. You can now do something like `generateBlendedMaterial(textures, new MeshStandardMaterial())` and it will use a standard material as the base. No guarantees that everything will work as expected, but it doesn't seem to break anything!
