### ISSUE TITLE
physics support ?

### ISSUE THREAD

**Issue by dreammonkey** [IceCreamYou/THREE.Terrain#28]
is there a way to export the heightmap so it can be re-used in physics engines like CANNON ? (even for large terrains ?)

**Comment by IceCreamYou** [comment]
Yes, this is [described in the README](https://github.com/IceCreamYou/THREE.Terrain#exporting-and-importing) and has also been asked in a [previous issue](https://github.com/IceCreamYou/THREE.Terrain/issues/19).

If you don't literally mean "export" and what you actually want is to access the `THREE.Geometry` of a procedurally generated terrain that's already in-memory, that is also [illustrated in the README](https://github.com/IceCreamYou/THREE.Terrain#procedurally-generate-a-terrain).
