### ISSUE TITLE
I m facing error using your library

### ISSUE THREAD

**Issue by blaxezcode** [IceCreamYou/THREE.Terrain#30]
![Screenshot_2021-09-03-15-32-15-785_com.android.chrome.jpg](https://user-images.githubusercontent.com/83776025/131988084-7550a711-ed34-4fb3-b276-59e7d1464582.jpg)

**Comment by blaxezcode** [comment]
New learner

**Comment by IceCreamYou** [comment]
You have to load [three.js](https://github.com/mrdoob/three.js) in the global scope before loading `THREE.Terrain`, otherwise the `THREE` variable will not be present to attach the `Terrain` property to.
