### ISSUE TITLE
Edges Documentation

### ISSUE THREAD

**Issue by eeonaa** [IceCreamYou/THREE.Terrain#31]
Hello, I have a basic terrain generation, and I am trying to add the THREE.terrain.edges function to my THREE.terrain object, but I cannot see how I would be able to use it. Is there any way you could provide an example or explanation on how I could apply this?

Thanks in advance.

**Comment by IceCreamYou** [comment]
Hello,

Pretty much ever feature of the library is demonstrated in the demo. [Here's the line](https://github.com/IceCreamYou/THREE.Terrain/blob/562488f3aa404a2c4a02c3bb29aebd8a2a180e3d/demo/index.js#L164) that uses THREE.Terrain.Edges. The easiest way to work with it is in the `after` hook as demonstrated in that link. Additionally you can read the method's own documentation [here](https://github.com/IceCreamYou/THREE.Terrain/blob/562488f3aa404a2c4a02c3bb29aebd8a2a180e3d/src/filters.js#L37).

Hope that helps.
