### ISSUE TITLE
Calculating heights between segments (Interpolation)

### ISSUE THREAD

**Issue by c4b4d4** [IceCreamYou/THREE.Terrain#32]
I'm using the following method to retrieve the heights of the terrain.

`const array = THREE.Terrain.toArray1D(geometry.attributes.position.array, {stretch:true, ...options});`

This works great, I've got all Y-positions of the terrain, in a width*height long 1D-Array.

But...

What about calculating a Y-position of the heightmap on positions that are not integers, e.g. coordinate **(10.58,12.13)**. I use to just round the number, so it'll become **(11,12)**, but that would give a wrong height in **steep terrains**.

Lookig online I found some helpful links ([Terrain interpolation algorithm](https://forum.unity.com/threads/terrain-interpolation-algorithm.163935/)), but cannot find the best algorithm to fit all kind of steep terrains.

One of the algorithms I tried is in [here (GetTerrainHeightInlined)](https://github.com/chanfort/Terrain-heightmap-manual-interpolation/blob/b99eb78e57cc835a44470babe674a6e8d09262b0/Assets/Scripts/TerrainUtils.cs). Which converted into JavaScript on my side looks like this:

```
const array = THREE.Terrain.toArray1D(geometry.attributes.position.array, {stretch:true, ...options});
const x = position.x * (res/size); //terrain is square sized
const z = position.z * (res/size);

const fx = Math.min(res-1,Math.max(0, Math.floor(x)));
const fz = Math.min(res-1,Math.max(0, Math.floor(z)));
const cx = Math.min(res-1,Math.max(0, Math.ceil(x)));
const cz = Math.min(res-1,Math.max(0, Math.ceil(z)));

const hx0z0 = array[fz*size + fx] || 0;
const hx1z0 = array[fz*size + cx] || 0;
const hx0z1 = array[cz*size + fx] || 0;
const hx1z1 = array[cz*size + cx] || 0;

const height = hx0z0 + (hx1z0 - hx0z0) * (lax - Math.floor(lax)) + (hx0z1 - hx0z0) * (laz - Math.floor(laz)) + (hx0z0 - hx1z0 - hx0z1 + hx1z1) * (lax - Math.floor(lax)) * (laz - Math.floor(laz));
```

I also tried a bi-linear algorithm, from the same link (GetTerrainHeightBilinear)

With both algorithms, I cannot get a decent heightmap interpolation between segments.

Do you have any suggestion? Has anyone come with a way to calculate these interpolations?

Thanks in advance.

**Comment by IceCreamYou** [comment]
Those algorithms assume a terrain based on quads, but with THREE.Terrain the terrain geometry is based on tris.

Take a look at [scatter.js](https://github.com/IceCreamYou/THREE.Terrain/blob/gh-pages/src/scatter.js) for an example of how this library places meshes at the correct height. It always places them at the center of the tris, so the position is just an average of the closest vertices: `mesh.position.addVectors(vertex1, vertex2).add(vertex3).divideScalar(3)`. However, the height at other locations is just a weighted average - something like `lerp(vertex1.y, vertex2.y, percentAcrossX) * (xWidth / (xWidth + zWidth)) + lerp(vertex2.y, vertex3.y, percentAcrossZ) * (zWidth / (xWidth + zWidth))` assuming vertex1 and vertex2 are x-aligned and vertex2 and vertex3 are y-aligned.

**Comment by IceCreamYou** [comment]
If you get tired of trying to work out the math, you can also just use a Raycaster and cast a ray straight down and use the intersection point. It's a lot slower, but that might not matter for your use case.

**Comment by c4b4d4** [comment]
> If you get tired of trying to work out the math, you can also just use a Raycaster and cast a ray straight down and use the intersection point. It's a lot slower, but that might not matter for your use case.

In my use case, I want to achieve it with math 😅. I need to run multiple validations, even server-side.

I will try your suggestion, will take a look at [scatter.js](https://github.com/IceCreamYou/THREE.Terrain/blob/gh-pages/src/scatter.js). Thank you.
