### ISSUE TITLE
Wrong variable name in scatter.js

### ISSUE THREAD

**Issue by c4b4d4** [IceCreamYou/THREE.Terrain#33]
I think that from your lasts commits, this variable didn't get changed:

https://github.com/IceCreamYou/THREE.Terrain/blob/562488f3aa404a2c4a02c3bb29aebd8a2a180e3d/src/scatter.js#L99

I think it should now be:

`randomness(i/9);`

'Cause loop now looks like this:

https://github.com/IceCreamYou/THREE.Terrain/blob/562488f3aa404a2c4a02c3bb29aebd8a2a180e3d/src/scatter.js#L91

**Comment by IceCreamYou** [comment]
Fixed, thank you. Good catch.
