### ISSUE TITLE
Example Request: Edges

### ISSUE THREAD

**Issue by austinmayer** [IceCreamYou/THREE.Terrain#4]
First off, incredible work with THREE.Terrain. This is by far the most seamless and comprehensive Terrain tool I've seen / used for Three.js. Keep it up!

Can you provide an example for how to implement the edge features? After digging around in the source / demo for documentation, I wasn't clear on usage. My last attempt was to use the `after` option to apply edge transformations, but no dice. 

Thanks in advance!

**Comment by IceCreamYou** [comment]
Glad you're finding the library useful!

The easiest way is to set the `after` option passed to `THREE.Terrain()` to a function like this one:

``` javascript
    function after(vertices, options) {
      THREE.Terrain.Edges( // or THREE.Terrain.RadialEdges(
        vertices,
        options,
        true, // true turns the edges up; false turns them down
        100, // how far from the edge the curvature should start
        THREE.Terrain. EaseInOut // or another curve function
      );
    };
```

**Comment by austinmayer** [comment]
Perfect, thanks dude!
